#!/usr/bin/env bash
#
# check-report-css-identical.sh — SELF-358 / P6 report-CSS regenerate-and-diff fence.
#
# Lock anchors:
#   - Architect's ruling `docs/records/v15-execution/self358-css-ruling.md` (Option A,
#     ratified 2026-09-06): a standalone Vite lib build (`api/vite.report-css.config.mjs`)
#     compiles the ~14 monthly-report components' scoped `<style>` blocks to ONE committed
#     plain CSS file, `api/src/lib/generated/report.css`, inlined by the PDF route via the
#     same `?raw` mechanism already used for `tokens.css`/`app.css`.
#   - This fence is BELT-AND-BRACES per the ruling's own text: "The CI regenerate-and-diff
#     fence is belt-and-braces on top of it [QA's hash-coverage assertion], not the primary
#     control." QA's assertion (every `svelte-[a-z0-9]+` token in the rendered body appears
#     in at least one selector in the extracted CSS) is the PRIMARY control for the failure
#     mode the ruling names — the SSR server build and this SEPARATE standalone build could
#     diverge. This fence is a cheaper, deterministic SECOND layer proving the specific
#     bytes committed to the repo are exactly what `npm run build:report-css` emits right
#     now, on the PR head, from source.
#
# WHAT THIS FENCE WATCHES:
#   Build drift between the report component tree's scoped CSS (as the standalone Vite lib
#   build currently emits it) and the committed artifact at `api/src/lib/generated/report.css`.
#   It goes RED on:
#     (a) a component's `<style>` block edited without re-running `build:report-css` and
#         re-committing the output (stale artifact),
#     (b) the committed artifact hand-edited directly (diverges from anything the build
#         would ever produce),
#     (c) the committed artifact deleted (diff against the regenerated-but-uncommitted
#         file is non-empty; fail-closed, never pass-by-absence).
#
# WHAT THIS FENCE CANNOT SEE:
#   A selector that EXISTS in the CSS but is WRONG for the rendered markup — e.g. a
#   `.svelte-XXXXXX` scoping-hash rule this build faithfully emits, that does not actually
#   match any class the rendered `body` uses (a selector-CONTENT bug, not a staleness bug).
#   This fence only proves "the committed file equals fresh build output right now"; it has
#   no opinion on whether that output is semantically correct for the rendered document.
#   That is QA's hash-coverage assertion's job (the PRIMARY control per the ruling) — this
#   fence does not substitute for it, and passing here is not evidence the PDF renders
#   styled.
#
# MECHANISM — real regenerate, not a static two-file byte-compare (same principle as
# check-dedup-hash-identical.sh, ADR-034 D4 Sec ratify condition 2: a static compare passes
# if both sides were hand-edited in lockstep, so it must not be used here either).
# `npm run build:report-css` is run FOR REAL from `api/`, in-place onto the real generated
# path (the standalone Vite config hardcodes its `outDir`; a Vite build has no `--stdout`
# mode the way the dedup-hash generator does), and the freshly regenerated bytes are diffed
# against a REFERENCE snapshot captured BEFORE the build runs. By default that reference is
# the target file's own pre-build on-disk content — this fence never shells to `git show` /
# `git diff --exit-code`, so it is git-index-state-independent (identical behavior on a
# clean checkout, a just-cloned PR head, or a dirty local working copy) — the same
# independence rationale check-dedup-hash-identical.sh's header argues for `--stdout | diff`
# over `git diff --exit-code`.
#
# ⚠ DELIBERATE DEVIATION from a literal `git diff --exit-code -- <target>` reading of the
#   SELF-358-devops brief: git-diff-against-the-index would false-GREEN a target that is
#   staged-but-differs-from-HEAD in a way that happens to match the working tree, and is
#   sensitive to whatever the runner's checkout step left staged. The pre-build-snapshot
#   form catches the same three failure modes (a)/(b)/(c) above without that sensitivity.
#   Flagged for Sec joint-review, not applied unilaterally.
#
# Dual-mode via --reference (mirrors check-dedup-hash-identical.sh's --source/--copy):
#   PRODUCTION  — no --reference: diff fresh build output against the target's own
#                 pre-build committed content -> expect exit 0 on a clean tree.
#   INVERSION   — --reference tests/fixtures/ci/report-css-drift-corrupted.css: diff fresh
#                 build output against a golden fixture that is the real committed artifact
#                 plus one appended corrupting CSS comment -> MUST differ -> expect exit 1.
#
# Usage:
#   bash scripts/ci/check-report-css-identical.sh
#     [--api-dir <path>]     (default: api)
#     [--target <path>]      (default: api/src/lib/generated/report.css; repo-root relative)
#     [--build-cmd <cmd>]    (default: npm run build:report-css)
#     [--reference <path>]   (default: none -> use the target's own pre-build content)
#
# Run from the repo root (matches the other security/web CI fences).
#
# Exit codes (three-way, mirrors fence-rt22-pdf-worker-dockerfile.sh /
# check-dedup-hash-identical.sh):
#   0 — committed artifact IS current build:report-css output (clean).
#   1 — DRIFT: fresh build output differs from the reference, or the target is missing
#       before or after a successful build (fail-closed — an unverifiable target is
#       treated as drift, never as a silent pass).
#   2 — argument / environment error: api-dir or npm missing, the build command itself
#       failed (nonzero exit — e.g. `build:report-css` script absent from package.json),
#       or a given --reference file is unreadable.

set -euo pipefail

API_DIR="api"
TARGET="api/src/lib/generated/report.css"
BUILD_CMD="npm run build:report-css"
REFERENCE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --api-dir)   API_DIR="${2:-}"; shift 2 ;;
    --target)    TARGET="${2:-}"; shift 2 ;;
    --build-cmd) BUILD_CMD="${2:-}"; shift 2 ;;
    --reference) REFERENCE="${2:-}"; shift 2 ;;
    *) echo "FATAL: unknown argument: $1" >&2
       echo "Usage: bash $(basename "$0") [--api-dir <path>] [--target <path>] [--build-cmd <cmd>] [--reference <path>]" >&2
       exit 2 ;;
  esac
done

if [ ! -d "$API_DIR" ]; then
  echo "FATAL: api-dir not found at: $API_DIR" >&2
  exit 2
fi
if ! command -v npm >/dev/null 2>&1; then
  echo "FATAL: npm not found on PATH (build:report-css is an npm script)." >&2
  exit 2
fi

REF_FILE="$REFERENCE"
if [ -z "$REF_FILE" ]; then
  if [ ! -f "$TARGET" ]; then
    echo "check-report-css fence: DRIFT — target missing at $TARGET before build; nothing to compare against (fail-closed)." >&2
    exit 1
  fi
  REF_FILE="$(mktemp)"
  cp "$TARGET" "$REF_FILE"
  trap 'rm -f "$REF_FILE"' EXIT
else
  if [ ! -f "$REF_FILE" ]; then
    echo "FATAL: --reference file not found at: $REF_FILE" >&2
    exit 2
  fi
fi

# Real regenerate, for real, from api-dir. A missing/misnamed build:report-css script (or
# any other build failure) is an ENVIRONMENT error, not drift — exit 2, never a silent pass.
if ! ( cd "$API_DIR" && eval "$BUILD_CMD" ); then
  echo "FATAL: build command failed: '$BUILD_CMD' (run from $API_DIR)." >&2
  exit 2
fi

if [ ! -f "$TARGET" ]; then
  echo "check-report-css fence: DRIFT — target missing at $TARGET after a successful build (fail-closed)." >&2
  exit 1
fi

# Quiet compare (`-q`), not `diff -u`: report.css is machine-minified to effectively one
# line, so a unified diff on drift would dump the entire ~37KB file as a single changed
# "line" twice over — noise, not signal. `cmp` gives a byte-offset instead.
if diff -q "$REF_FILE" "$TARGET" >/dev/null; then
  echo "check-report-css fence: $TARGET IS current build:report-css output (no drift)."
  exit 0
else
  echo "" >&2
  echo "check-report-css fence: DRIFT — $TARGET does not match the reference (SELF-358 / P6)." >&2
  echo "  reference: $REF_FILE ($(wc -c < "$REF_FILE") bytes)" >&2
  echo "  target:    $TARGET ($(wc -c < "$TARGET") bytes)" >&2
  echo "  first byte-level difference:" >&2
  cmp "$REF_FILE" "$TARGET" >&2 || true
  echo "" >&2
  echo "Do not hand-edit the generated CSS. Fix at source:" >&2
  echo "  1. Edit the report component(s)' <style> blocks under api/src/lib/components/." >&2
  echo "  2. Regenerate: (cd api && npm run build:report-css)" >&2
  echo "  3. Commit the regenerated $TARGET." >&2
  exit 1
fi
